"""Compose a resolved canary cell into the exact prompts and parameters it runs with.

The frozen prompt bundle's ``condition_composition`` map already states which template
families make up each condition, so this module reads that map rather than hardcoding
per-kind logic. The map is also what distinguishes the two judgment shapes:

- an entry carrying ``judge`` is a **single call** (the batch replay and the two
  diagnostics): one prompt in, one verdict out, no query loop;
- an entry carrying ``presentation`` and ``verdict`` takes **judge_loop's shape**:
  presentation, an optional gated query loop, then a verdict.

``judge_loop.run_judgment`` reads its prompts out of a protocol-shaped dict, so the second
shape is served by building that dict from the bundle rather than by forking judge_loop. That
keeps one implementation of the query loop, which is the part the science depends on.

Anything the bundle does not state is refused rather than defaulted.
"""
from __future__ import annotations

import re
from typing import Any, Mapping

from rejudge.phase2_canary_cells import ResolvedCell

# The frozen no-query transition shown when a slot is consumed without a dispatch. Still
# provisional pending oracle review, which is why it is composed here and injected into the
# gate rather than written into the gate's own logic.
PROVISIONAL_NO_QUERY_PAYLOAD = "No verification result is available for this query."

_PLACEHOLDER = re.compile(r"\{(\w+)\}")


class UncomposableCell(ValueError):
    """Raised when a cell cannot be composed from the frozen bundle."""


def _require_judgment(cell: ResolvedCell) -> Mapping[str, Any]:
    if cell.is_transcript:
        raise UncomposableCell(
            f"cell {cell.cell_key} is a transcript; transcripts are generated by debate_gen, "
            "not composed as judgments")
    return cell.composition


def is_single_call(cell: ResolvedCell) -> bool:
    """True when the bundle composes this condition as one prompt rather than a loop."""
    composition = _require_judgment(cell)
    if "judge" in composition:
        return True
    if "presentation" in composition and "verdict" in composition:
        return False
    raise UncomposableCell(
        f"condition {cell.condition!r} composes neither a judge template nor a "
        f"presentation/verdict pair: {sorted(composition)!r}")


def judge_protocol_for(cell: ResolvedCell, protocol: Mapping[str, Any],
                       bundle: Mapping[str, Any]) -> dict[str, Any]:
    """Build the protocol-shaped dict ``judge_loop.run_judgment`` reads.

    ``query_phase_prompt`` is the frozen phase-2 template in final form, so the caller passes
    it to run_judgment as ``query_template_override``: the Stage-1 rewrite would raise on it,
    since it contains no pilot phrasing line to rewrite.
    """
    if is_single_call(cell):
        raise UncomposableCell(
            f"condition {cell.condition!r} is a single-call judgment; use single_call_prompt")
    composition = cell.composition
    templates = bundle["templates"]
    presentation = templates[composition["presentation"]]
    verdict = templates[composition["verdict"]]

    query_phase_prompt = None
    if "query" in composition:
        query_phase_prompt = templates[composition["query"]]["user_prompt_template"]

    oracle = templates[composition["oracle"]] if "oracle" in composition else (
        templates["oracle"])

    temperatures = protocol["decisions"]["execution_semantics"]["temperature_by_call_role"]
    gate: dict[str, Any] = {
        "rejection_payload": (templates[composition["rejection"]]["payload"]
                              if "rejection" in composition else None),
        "no_query_payload": PROVISIONAL_NO_QUERY_PAYLOAD,
        "checker_template": composition.get("checker"),
    }

    return {
        "judge": {
            "system_prompt": presentation["system_prompt"],
            "user_prompt_template": presentation["user_prompt_template"],
            "query_phase_prompt": query_phase_prompt,
            "verdict_prompt": verdict["user_prompt_template"],
        },
        "oracle": {
            "system_prompt": oracle["system_prompt"],
            "user_prompt_template": oracle["user_prompt_template"],
        },
        "protocol": {
            "models": {"oracle": protocol["roster"]["oracle"]},
            "temperature": {
                "judge": temperatures["judge_verdict"],
                "oracle": temperatures["oracle"],
                "debater": temperatures["debater"],
            },
        },
        "gate": gate,
    }


def single_call_prompt(cell: ResolvedCell, bundle: Mapping[str, Any],
                       **fields: Any) -> tuple[str, str]:
    """Build (system, user) for a single-call judgment.

    Every placeholder the frozen template declares must be supplied. A missing one would
    otherwise raise deep inside ``str.format`` or, worse, render blank and quietly change what
    the judge was shown.
    """
    if not is_single_call(cell):
        raise UncomposableCell(
            f"condition {cell.condition!r} is not a single-call judgment")
    template = bundle["templates"][cell.composition["judge"]]
    user_template = template["user_prompt_template"]
    required = set(_PLACEHOLDER.findall(user_template))
    missing = required - fields.keys()
    if missing:
        raise UncomposableCell(
            f"condition {cell.condition!r} needs {sorted(missing)!r} to compose its prompt")
    return template["system_prompt"], user_template.format(
        **{name: fields[name] for name in required})
